name: Homeward
version: 1.0.3
author: Kiteflow
main: dev.kiteflow.homeward.Homeward
commands:
  deletehome:
    description: Deletes a player home
    aliases: [delhome]
  home:
    description: Teleport to a player home
  homes:
    description: View your homes
  sethome:
    description: Sets a player home